---
title: "Prepare Matrix Data"

output:
  html_document:
    df_print: paged
    toc: yes
  html_notebook:
    number_sections: yes
    toc: yes

knit: (function(input_file, encoding) {
  out_dir <- '../html';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, '01_01_prepare_matrix_data.html'))})
---

#### Define Libraries
```{r echo=TRUE, message=FALSE, warning=FALSE, tidy=TRUE}
library("stringr")
```

#### Define Path
```{r tidy=TRUE}
dir.wrk <- str_replace(getwd(), "/scripts", "")
dir.data <- file.path(dir.wrk, "data/GSE103224_RAW")
dir.des <- file.path(dir.wrk, "data/design")
dir.output <- file.path(dir.wrk, "data/gene_matrix")
```

#### Get Matrix Files
```{r tidy=TRUE}
files.mat <- list.files(path=dir.data, pattern="txt.gz", full.names = FALSE)
```

#### Get Genes
```{r}
#for(i in 1:length(files.mat)){
for(i in 1:1){  
  file.mat <- file.path(dir.data, files.mat[[i]])
  dat <- read.delim2(file.mat, header=FALSE, stringsAsFactors=FALSE)
  print(dim(dat))
}
```

